## connection management

In [4]:
# one_to_one

from nest import *

ResetKernel()

n = 3
A = Create("iaf_psc_alpha", n)
B = Create("spike_detector", n)
Connect(A, B, 'one_to_one')
# weight = 1.5
# delay = 0.5
# syn_dict = {'weight':weight, 'delay':delay}
# Connect([A[0]], [B[0]], syn_spec= syn_dict)



for i in range(3):
    conn = GetConnections([A[i]])
    print GetStatus(conn, ['source','target'])



((1, 4),)
((2, 5),)
((3, 6),)


In [9]:
# all_to_all

from nest import *

ResetKernel()

n, m = 2, 2
A = Create("iaf_psc_alpha", n)
B = Create("iaf_psc_alpha", n)

# B = Create("spike_detector", m)
Connect(A, B)
Connect(B, A)

for i in range(n):
    conn = GetConnections([A[i]])
    print GetStatus(conn, ['source','target'])

for i in range(n):
    conn = GetConnections([B[i]])
    print GetStatus(conn, ['source','target'])


((1, 3), (1, 4))
((2, 3), (2, 4))
((3, 1), (3, 2))
((4, 1), (4, 2))


In [12]:
#fixed_in_degree
from nest import *
ResetKernel()

n, m, N = 5, 6, 2
A = Create("iaf_psc_alpha", n)
B = Create("iaf_psc_alpha", m)
conn_dict = {'rule': 'fixed_indegree', 'indegree': N}
Connect(A, B, conn_dict)

# for i in range(n):
#     conn = GetConnections([A[i]])
#     print GetStatus(conn, ['source','target'])

# print ' '

# conns = GetConnections(target=B)
conns = GetConnections(source=A)
print GetStatus(conns, ['source', 'target'])

((1, 6), (1, 11), (2, 7), (2, 11), (2, 6), (2, 8), (2, 10), (2, 9), (2, 10), (4, 9), (4, 8), (5, 7))


In [6]:
import numpy as np
def adj_list_to_matrix(adj_list):
    A = np.asarray(adj_list)
    
    n = np.max(np.asarray(adj_list))
    adj_matrix = np.zeros((n,n), dtype=int)

    for i in range(A.shape[0]):
        for j, k in adj_list[i]:
            adj_matrix[j-1,k-1] = 1
    return adj_matrix

adj_list = [((1, 4), (1, 5), (1, 6), (1, 7)),
            ((2, 4), (2, 5), (2, 6), (2, 7)),
            ((3, 4), (3, 5), (3, 6), (3, 7))]

print adj_list_to_matrix(adj_list)


[[0 0 0 1 1 1 1]
 [0 0 0 1 1 1 1]
 [0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [15]:
#fixed_out_degree
from nest import *
ResetKernel()

n, m, N = 5, 6, 2
A = Create("iaf_psc_alpha", n)
B = Create("iaf_psc_alpha", m)
conn_dict = {'rule': 'fixed_outdegree', 'outdegree': N}
Connect(A, B, conn_dict)

for i in range(n):
    conn = GetConnections([A[i]])
    print GetStatus(conn, ['source','target'])


((1, 8), (1, 7))
((2, 9), (2, 7))
((3, 6), (3, 7))
((4, 8), (4, 11))
((5, 9), (5, 8))


-  fixed-total-number

The nodes in pre are randomly connected with the nodes in post such that the total number of connections equals N.

In [16]:
# fixed-total-number
from nest import *
ResetKernel()

n, m, N = 5, 6, 10
A = Create("iaf_psc_alpha", n)
B = Create("iaf_psc_alpha", m)
conn_dict = {'rule': 'fixed_total_number', 'N': N}
Connect(A, B, conn_dict)

for i in range(n):
    conn = GetConnections([A[i]])
    print GetStatus(conn, ['source','target'])


((1, 7), (1, 9))
((2, 6), (2, 11), (2, 7), (2, 11), (2, 10))
((3, 9),)
((4, 7), (4, 7))
()


-  pairwise-bernoulli

For each possible pair of nodes from pre and post, a connection is created with probability p.

In [14]:
from nest import *

ResetKernel()

n, m, p = 5, 6, 0.2
A = Create("iaf_psc_alpha", n)
B = Create("iaf_psc_alpha", m)
conn_dict = {'rule': 'pairwise_bernoulli', 'p': p}
Connect(A, B, conn_dict)        


for i in range(n):
    conn = GetConnections([A[i]])
    print GetStatus(conn, ['source','target'])


((1, 8), (1, 11))
((2, 6),)
((3, 8), (3, 11))
()
()


In [16]:
helpdesk()